### ISSUE TITLE
AWS AppSync generated GraphQL issue

### ISSUE THREAD

**Issue by blackmouth** [aws-samples/aws-mobile-appsync-events-starter-ios#11]
The example GraphQL shows it including $ characters while the version I grab from the AWS AppSync dashboard does not.   Is there .graphqlconfig  missing to generate a proper GraphQL?

mutation DeleteEvent($id: ID!) {
  deleteEvent(id: $id) {
    id
    description
    name
  }
}

https://github.com/awslabs/aws-appsync-codegen/issues/6

**Comment by undefobj** [comment]
@blackmouth those are query variables, which you can optionally use in the GraphQL file that you create (not the introspection schema which is what you download from the console).

**Comment by blackmouth** [comment]
@undefobj Thank you. I was using the introspection schema downloaded from the console and had not typed out my own GraphQL file to use with aws-appsync-codegen generate.
