### ISSUE TITLE
Pagination of Graph query is not provided

### ISSUE THREAD

**Issue by kerimovscreations** [aws-samples/aws-mobile-appsync-events-starter-ios#13]
Graph API for GetAllEvents query is provided with pagination support, but this functionality is not demonstrated in the example project.

**Comment by rohandubal** [comment]
Hello @kerimovscreations 

Any specific use-case you are trying to see in the example project? The pagination query is part of the generated schema and you can use it by providing the pagination token.

Thanks,
Rohan

**Comment by kerimovscreations** [comment]
Thanks for the response.

I would like to see, how pagination will be applied to table view after list elements' count exceeds the query limit.

**Comment by cbommas** [comment]
@kerimovscreations 
I have added this as a feature request in our backlog and have submitted to the team for prioritization. I do not have a specific timeline that I can share at this point. We will let you know, either on this thread, or through a forum announcement when the sample is updated.

**Comment by kerimovscreations** [comment]
@cbommas 
Thanks for a response. Is your team open for contributions? I would like to pull request my solution for this feature.

**Comment by cbommas** [comment]
@kerimovscreations 

Absolutely. Please go ahead and submit a PR and we will work through it with you.

**Comment by rohandubal** [comment]
Closing this issue, since we will track it further in a PR.
