### ISSUE TITLE
Failed to add comments on the last event_item you just added, because the item_id always equals to -1.

### ISSUE THREAD

**Issue by HarveyHu** [aws-samples/aws-mobile-appsync-events-starter-ios#3]
▿ 9 : Optional<Item>                  <---------------the last event_item I just added.
      ▿ some : Item
        ▿ snapshot : 7 elements
          ▿ 0 : 2 elements
            - key : "name"
            ▿ value : Optional<Any>
              - some : "one more"
          ▿ 1 : 2 elements
            - key : "__typename"
            ▿ value : Optional<Any>
              - some : "Event"
          ▿ 2 : 2 elements
            - key : "id"
            ▿ value : Optional<Any>
              - some : "-1"                   <---------------always be '-1'
          ▿ 3 : 2 elements
            - key : "description"
            ▿ value : Optional<Any>
              - some : "11"
          ▿ 4 : 2 elements
            - key : "comments"
            - value : nil
          ▿ 5 : 2 elements
            - key : "when"
            ▿ value : Optional<Any>
              - some : "11"
          ▿ 6 : 2 elements
            - key : "where"
            ▿ value : Optional<Any>
              - some : "11"

**Comment by rohandubal** [comment]
Hello @HarveyHu, 

Sorry that you are having trouble using the SDK. Could you please answer couple questions so that I can diagnose the problem?
- Are you doing optimistic writes on the cache?
- Does using optimistic IDs (random UUIDs) other than -1 help resolve the problem?
- Could you provide a sample code for reproducing this issue?

Thanks,
Rohan

**Comment by HarveyHu** [comment]
No worries, @rohandubal ,

What do you mean by 'optimistic writes' and 'optimistic ID'?
I didn't change your code, and you can reproduce it by:
1. add an event_item
2. go to the last event you just added, and then try to add some comments on it.
3. those comments won't sync to the server correctly.

All the best
Harvey

**Comment by rohandubal** [comment]
We have now updated the sample to use a random UUID instead of -1. If multiple events are added, they should not over-write. Temporary IDs go away once query is re-fetched.

Thanks,
Rohan
