### ISSUE TITLE
Pod install fails to load the library

### ISSUE THREAD

**Issue by rcfrias** [aws-samples/aws-mobile-appsync-events-starter-ios#4]
Pod install fails to load the library,
Following message is shown:
Unable to find a specification for `AWSAppSync (~> 2.6)`

**Comment by kvasukib** [comment]
Hi @rcfrias, Did you run pod repo update before attempting to run pod install?

**Comment by kredden** [comment]
Hi, can you post the contents of your podfile and all the errors you are seeing when you run "pod install --repo-update"?

Thanks,
Kevin
